########## 数据库:待扩展--主从与哨兵模式 ##########
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:33061/z7_user_auth?useSSL=false&autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC
    username: root
    password: qwer1234#
    redis:
      port: 60379
      database: 0
      host: localhost
      password: qwer1234#

########### 暴露监控端点 ##########
management:
  endpoints:
    web:
      exposure:
        include: '*'