########### TOMCAT配置 ##########
server:
  tomcat:
    accept-count: 800
    max-connections: 1200
    max-threads: 600

########### ORM ##########
mybatis:
  mapper-locations:
    - classpath:com.z7.bespoke.**.mapper/*.xml
  type-aliases-package: com.z7.bespoke.**.mapper.po
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

########### 分页插件 ##########
pagehelper:
  helper-dialect: mysql
  params: count=countSql
  reasonable: false
  support-methods-arguments: true

########### 网关过滤配置 ##########
filter:
  signature:
    enabled: true
    noNeedFilterUrlPatterns: [ /home/door_system/notify ]
    needFilterUrlPatterns: [ /user/** ]
    key-details: [ { companyCode: Z&DEV, apiKey: 1153f8d42937553bd884b77dabd90097, securityKey: 0ddec2e0b94ad44859f726ec9f35d442 },
                   { companyCode: Z&TEST, apiKey: 62ba0f94f3e4c760f7d48685672a2a08, securityKey: 611f7814b038228ac5c32e15ae471364 },
                   { companyCode: Z&OTHER, apiKey: e31f9f015b7b990827a1fb3dbaeb19b9, securityKey: f1c36a0398cbb867b31515400555506d } ]

########### 配置中心测试 ##########
foo: 网关中心-V1.0.1.default
