#server:
#  tomcat:
#    accept-count: 800
#    max-connections: 1200
#    max-threads: 600
#
########### ORM ##########
#mybatis:
#  mapper-locations:
#    - classpath:com.z7.bespoke.**.mapper/*.xml
#  type-aliases-package: com.z7.bespoke.**.pojo.po
#  configuration:
#    map-underscore-to-camel-case: true
#
########### 分页插件 ##########
#pagehelper:
#  helper-dialect: mysql
#  params: count=countSql
#  reasonable: false
#  support-methods-arguments: true

########### 配置中心测试 ##########
foo: 网关中心-V1.0.1.default
