server:
  # 注册服务的端口号
  port: 7001
  application:
    name: discoery

spring:
  ##配置环境
  profiles:
    active: dev

eureka:
  server:
    ##关闭自我保护机制，保证不可用服务被及时踢除,默认是开启的
    enable-self-preservation: false
  instance:
    ##eureka服务端的实例名称,集群时候避免重名
    hostname: localhost
    ##访问路径时不显示ip false=不显示
    prefer-ip-address: true
    instance-id: ${eureka.instance.hostname}:${server.port}
  client:
    ##false表示不向注册中心注册自己
    register-with-eureka: false
    ##false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    fetch-registry: false
    serviceUrl:
      ##配置单机/集群
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

 